"""Corrigindo atributo unique da coluna password

Revision ID: c65e3b600f8d
Revises: 3cfe4a984f72
Create Date: 2023-11-17 18:44:23.874790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c65e3b600f8d'
down_revision: Union[str, None] = '3cfe4a984f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_password', table_name='users')
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.create_index('ix_users_password', 'users', ['password'], unique=False)
    # ### end Alembic commands ###
