name: Build Workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'

    - name: Cache de instalação do Poetry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Instalar Poetry
      run: pip install poetry

    - name: Cache das dependências
      uses: actions/cache@v3
      with:
        path: |
            ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Instalar Dependências
      run: poetry install

    - name: Checando se houve alterações no backend
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          backend:
            - 'backend/**'

    - name: Testes do backend
      if: steps.changes.outputs.backend == 'true'
      run: poetry run task test
      env:
        DATABASE_URL: ${{ vars.DATABASE_URL }}
